service: s3-local-flatmap-issue
provider:
  name: aws
  runtime: nodejs8.10
plugins:
  - serverless-s3-local
  - serverless-offline
custom:
  s3:
    host: 0.0.0.0
    port: 8000
    directory: /tmp

resources:
  Resources:
    NewResource:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: local-bucket

functions:
  webhook:
    handler: index.webhook
    events:
      - http:
        method: GET
